Sprint1/step2
Elizaveta-1207/react-burger pull request #2
Opened 2021-11-19 19:09 UTC by Elizaveta-1207

Did the second part of 1 sprint

2021-11-19 19:19 UTC, grishbar commented
`надо исправить` Привет, для начала обрати внимание, что пулл-реквест должен быть создан из ветки sprint-1/step-2 в main

2021-11-19 19:28 UTC, grishbar commented
При клике на табы "булки", "соусы", "начинки" твой компонент должен проскроливаться до этой категории, и соответственно таб становится активным. Также при обычном скролле burgeringredients активный таб меняется при доскролле до определенной категории, чтобы это реализовать тебе поможет [useRef](https://ru.reactjs.org/docs/hooks-reference.html#useref) и [scrollIntoView](https://www.carlrippon.com/scrolling-a-react-element-into-view/)
![Screen Shot 2021-11-19 at 22 22 59](https://user-images.githubusercontent.com/32193933/142679815-6cd563e8-b084-4170-a072-0f075ba6f400.png)

2021-11-19 19:31 UTC, grishbar commented
`надо исправить` посмотри внимательней на макет, слева от ингредиентов в burger-constructor у тебя должны быть иконки с 6 точками
![Screen Shot 2021-11-19 at 22 30 04](https://user-images.githubusercontent.com/32193933/142680675-037716fa-df52-4a39-a11a-0ad88140c39b.png)

2021-11-19 20:07 UTC, grishbar requested changes
В целом очень хорошая работа, прекрасно реализовала модальное окно, абсолютно верно воспользовалась порталом, во всей работе выдержан одинаковый стиль, твой код легко и просто читается, круто, что все сделано на функциональных компонентах с деструктуризацией пропсов, но есть некоторые замечания, которые необходимо поправить для принятия работы:

- [ ] пулл-реквест должен быть создан из ветки sprint-1/step-2 в main
- [ ] Табы в ингредиентах должны корректно работать
- [ ] Добавить слева от ингредиентов в burger-constructor иконки с 6 точками
- [ ] Удалить все ненужные комментарии
- [ ] Переименовать все некорректно или плохо названные переменные
- [ ] Избавиться от дублирования кода
- [ ] Удалить все console.log
- [ ] Также у тебя если в качестве пропсов передается объект или массив объектов, то в propTypes нужно описать структуру этого объекта

2021-11-19 20:07 UTC, grishbar commented on src/components/App/App.jsx
> +// import data from '../../utils/data.json';
`надо исправить` все комментарии не документуриющие код(которые не описывают, что происходит в строчках под ними) должны быть удалены

2021-11-19 20:07 UTC, grishbar commented on src/components/App/App.jsx
> +const API = 'https://norma.nomoreparties.space/api/ingredients';
`надо исправить` это не api у тебя, api могло бы выглядеть вот так - https://norma.nomoreparties.space/api , тут у тебя ссылка, чтобы получить ингредиенты, так ее и назови

2021-11-19 20:07 UTC, grishbar commented on src/components/App/App.jsx
> +  const [data, setData] = React.useState();
`надо исправить` data очень плохое название, там может храниться все что угодно, давай переименуем переменную так, чтобы было понятно, что она содержит

2021-11-19 20:07 UTC, grishbar commented on src/components/App/App.jsx
> +  const [ingerients, setIngredients] = React.useState([]);
`надо исправить` тут опечатка

2021-11-19 20:07 UTC, grishbar commented on src/components/App/App.jsx
> +  };
`надо исправить` это функции а значит они выполняют какие то действия, соответственно в названиие переменной должен быть глагол а не существительное, + эти две функции дублируют друг друга в твоем случае это должно выглядеть так:
```
  const setModalType = (type) => {
    setModalType(type);
  };
```
даже необязательно выносить в отдельную функцию, можно сразу передать стрелочную функцию в пропсу

2021-11-19 20:07 UTC, grishbar commented on src/components/App/App.jsx
> +  console.log(modalType);
`надо исправить` console.log быть в рабочей версии проекта не должно, просматривай код перед или сразу после отправки на ревью

2021-11-19 20:07 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +function BurgerConstructor({ data, onModalOpen, getModalType }) {
`отлично` круто, что все переделала на функциональные компоненты и деструктурируешь пропсы

2021-11-21 07:27 UTC, Elizaveta-1207 commented
> `надо исправить` Привет, для начала обрати внимание, что пулл-реквест должен быть создан из ветки sprint-1/step-2 в main

Добрый день!
По согласованию с наставником (Влад Манаков) данный пункт можно рассматривать, как `можно лучше`.

2021-11-21 07:27 UTC, Elizaveta-1207 commented on src/components/App/App.jsx
> +  const [data, setData] = React.useState();
По согласованию с наставником (Влад Манаков) данный пункт можно рассматривать, как `можно лучше`.

2021-11-21 07:29 UTC, Elizaveta-1207 commented
> `надо исправить` При клике на табы "булки", "соусы", "начинки" твой компонент должен проскроливаться до этой категории, и соответственно таб становится активным. Также при обычном скролле burgeringredients активный таб меняется при доскролле до определенной категории, чтобы это реализовать тебе поможет [useRef](https://ru.reactjs.org/docs/hooks-reference.html#useref) и [scrollIntoView](https://www.carlrippon.com/scrolling-a-react-element-into-view/) ![Screen Shot 2021-11-19 at 22 22 59](https://user-images.githubusercontent.com/32193933/142679815-6cd563e8-b084-4170-a072-0f075ba6f400.png)

Уточнила у наставника (Влад Манаков). Данный пункт будет реализован во втором спринте.

2021-11-21 07:32 UTC, Elizaveta-1207 commented on src/components/App/App.jsx
> +  console.log(modalType);
Убрала

2021-11-21 07:36 UTC, Elizaveta-1207 commented on src/components/App/App.jsx
> +  const [ingerients, setIngredients] = React.useState([]);
Исправила

2021-11-21 07:36 UTC, Elizaveta-1207 commented on src/components/App/App.jsx
> +const API = 'https://norma.nomoreparties.space/api/ingredients';
Переименовала.

2021-11-21 07:37 UTC, Elizaveta-1207 commented on src/components/App/App.jsx
> +// import data from '../../utils/data.json';
Удалила.

2021-11-21 07:43 UTC, Elizaveta-1207 commented on src/components/App/App.jsx
> +  };
Поправила

2021-11-21 07:43 UTC, Elizaveta-1207 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +function BurgerConstructor({ data, onModalOpen, getModalType }) {
Спасибо :)

2021-11-21 09:18 UTC, Elizaveta-1207 commented
> `надо исправить` посмотри внимательней на макет, слева от ингредиентов в burger-constructor у тебя должны быть иконки с 6 точками ![Screen Shot 2021-11-19 at 22 30 04](https://user-images.githubusercontent.com/32193933/142680675-037716fa-df52-4a39-a11a-0ad88140c39b.png)

Реализовала

2021-11-21 19:14 UTC, grishbar commented
Отлично, все критичные проблемы исправила, код стал намного чище, работу засчитываю, да, насчет функционала с табами это в `можно лучше`, удачи в дальнейшем обучении.

2021-12-07 18:54 UTC, merged