Sprint 2/step 2
Elizaveta-1207/react-burger pull request #3
Opened 2021-12-10 00:56 UTC by Elizaveta-1207

Did the project of sprint 2

2021-12-10 14:14 UTC, grishbar requested changes
Очень достойная работа, весь код выдержан в одном стиле, легко читается, круто, что пользуешься usememo, и отлично сделала драг энд дроп ингредеинтов, и классно, что оставила там поясняющие комментарии 👍
Моменты которые нужно исправить для принятия работы:

- [ ] Согласно заданию надо добавить счетчик для ингредиентов
- [ ] Убрать создание функций из jsx
- [ ] Убрать дублирование кода
- [ ] Корректно обрабатывать ошибку при запросе в redux
- [ ] Переименовать неудачно названные переменные

Также можешь обратить внимание на комментарии "можно лучше" они помогут сделать твой код более качественным, удачи в рефакторинге.

2021-12-10 14:14 UTC, grishbar commented on src/components/App/App.jsx
> +export const BASE_API_URL = 'https://norma.nomoreparties.space/api';
`можно лучше`
в идеале это бы вынести в отдельный файл в utils/constant и во всех компонентах подтягивать оттуда

2021-12-10 14:14 UTC, grishbar commented on src/components/App/App.jsx
> +            }}
`надо исправить`
[нельзя создавать функции внутри jsx](https://qastack.ru/programming/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind), это очень плохо влияет на производительность, также вижу, что в других местах тоже так делаешь, поправь везде пожалуйста

2021-12-10 14:14 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  }, [constructorBuns, constructorIngredients]);
`можно лучше`
отлично место для использования useMemo, но можно лучше, тут можно воспользоваться [reduce](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce) и написать в одну строчку. Также reduce семантически лучше подходит тут

2021-12-10 14:14 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    const ingredientsId = constructorIngredients.map((item) => item._id);
`можно лучше`
ingredientIds

2021-12-10 14:14 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +        }}
`надо исправить`
[инлайновые стили не круто, такие стили тяжело поддерживать и редактировать](https://htmlacademy.ru/blog/boost/frontend/inline), избавься от них пожалуйста

2021-12-10 14:14 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                />
`надо исправить`
у тебя тут дублирование кода, можно легко сделать одним компонентом

2021-12-10 14:14 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                  item.type !== 'bun' && (
`можно лучше`
вначале отфильтруй массив при помощи [filter](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/filter), а потом проходи при помощи map по нему, получится куда красивее и читаемей

2021-12-10 14:14 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +              : 0}
`можно лучше`
ты считаешь сумму она по дефолту должна возвращать 0, тогда тут не придется эту неприятную логику невшивать

2021-12-10 14:14 UTC, grishbar commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +    // расстояние от верхушки табов до верхушки каждого блока с ингридиентами
`отлично`
хорошие комментарии, тут они очень даже полезны, молодец

2021-12-10 14:14 UTC, grishbar commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +    console.log(currentTab);
`надо исправить`
надо удалить console log

2021-12-10 14:14 UTC, grishbar commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +        </div>
`надо исправить`
у тебя тут дублирование кода, заведи один массив объектов или [Map](https://learn.javascript.ru/map-set) с title и ingredients, и пройдись по нему при помощи array.map

2021-12-10 14:14 UTC, grishbar commented on src/services/actions/burgerConstructor.jsx
> +    const uniqueId = Math.trunc(Math.random() * 100000000);
`можно лучше`
так тоже можно, но лучше будет если воспользуешься [uuid](https://www.npmjs.com/package/uuid)

2021-12-10 14:14 UTC, grishbar commented on src/services/actions/burgerConstructor.jsx
> +};
`надо исправить`
надо переделать, на то, чтобы всегда считать сумму исходя из текущих ингредиентов в хранилище, а не посредством экшенов, так будет более надежно, у тебя будет меньше источников данных, и соответственно меньше шансов ошибиться

2021-12-10 14:14 UTC, grishbar commented on src/services/actions/burgerIngredients.jsx
> +        else dispatch({ type: GET_BURGER_INGREDIENTS_ERROR });
`можно лучше`
else тут не нужен

2021-12-10 14:14 UTC, grishbar commented on src/services/reducers/burgerIngredients.jsx
> +        ...state,
`надо исправить
При ошибке в запросе надо возвращать - initialState и ingredientsError: true , так как не хочется держать в хранилище потенциально невалидные данные

2021-12-10 14:14 UTC, grishbar commented on src/services/reducers/burgerIngredients.jsx
> +  ingredientsError: false,
`надо исправить`
кажется это две булевые переменные и должны они называться соответственно:
isIngredientsLoading
isIngredientsGetFailed

2021-12-10 14:14 UTC, grishbar commented on src/services/reducers/ingredient.jsx
> +        ingredient: null,
`надо исправить`
тут надо просто вернуть initial state

2021-12-10 14:14 UTC, grishbar commented on src/services/reducers/order.jsx
> +export const orderReducer = (state = initialState, action) => {
`надо исправить`
в этом редьюсере тоже недо корректно обработать ошибку при запросе (вернуть initialstate) и правильно назвать булевые переменные

2021-12-14 12:29 UTC, Elizaveta-1207 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +        }}
сделала

2021-12-14 12:29 UTC, Elizaveta-1207 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                />
сделала

2021-12-14 13:20 UTC, Elizaveta-1207 commented on src/components/App/App.jsx
> +            }}
переписала через useCallback

2021-12-14 13:30 UTC, Elizaveta-1207 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +        </div>
поправила

2021-12-14 13:33 UTC, Elizaveta-1207 commented on src/services/reducers/burgerIngredients.jsx
> +  ingredientsError: false,
поправила

2021-12-14 13:33 UTC, Elizaveta-1207 commented on src/services/reducers/burgerIngredients.jsx
> +        ...state,
поправила

2021-12-14 13:35 UTC, Elizaveta-1207 commented on src/services/reducers/ingredient.jsx
> +        ingredient: null,
поправила

2021-12-14 13:37 UTC, Elizaveta-1207 commented on src/services/reducers/order.jsx
> +export const orderReducer = (state = initialState, action) => {
поправила

2021-12-14 14:01 UTC, Elizaveta-1207 commented on src/services/actions/burgerConstructor.jsx
> +};
поправила

2021-12-14 17:02 UTC, grishbar approved these changes
Отлично все критичные ошибки исправила, работу принимаю, постарайся исправить пожалуйста все новые комментарии, перед влитием, и будет совсем прекрасно, если поправишь еще все комментарии "можно лучше"

2021-12-14 17:02 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  const data = useSelector((state) => state.burgerIngredients.ingredients);
`надо исправить`
имя data слишком абстрактное, не очень понятно, что лежит в этой переменной, надо переименовать, тем более ты селектишь из стора state.burgerIngredients.ingredients, логично, что эта переменная будет называться ingredients, для консистентности данных

2021-12-14 17:02 UTC, grishbar commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  const sum = useMemo(() => {
`можно лучше`
почему бы не добавить сумму булки в этой функции, чтобы не пришлось в jsx лишние действия делать

2021-12-14 17:02 UTC, grishbar commented on src/components/Counter/Counter.jsx
> +      )}
`надо исправить`
получается сейчас, что если, amount <= 0 то ты отрисуешь пустой компонент Counter, это неправильно, сделай либо возвращай null в этом компоненте либо лучше сделай условную отрисовку в месте где используешь этот компонент

2021-12-14 17:02 UTC, grishbar commented on src/components/Ingredient/Ingredient.jsx
> +  const data = useSelector((state) => state.burgerIngredients.ingredients);
`надо исправить`
тут также надо переименовать переменную data

2021-12-14 17:02 UTC, grishbar commented on src/components/Ingredient/Ingredient.jsx
> +  }, [constructorBuns, constructorIngredients, buns, _id]);
`надо исправить`
каунтер у булки должен быть единицей если добавлена булка, а в интерфейсе отображаться как две булки

2022-01-05 10:36 UTC, Elizaveta-1207 commented on src/components/Ingredient/Ingredient.jsx
> +  const data = useSelector((state) => state.burgerIngredients.ingredients);
поправила

2022-01-05 10:36 UTC, Elizaveta-1207 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  const data = useSelector((state) => state.burgerIngredients.ingredients);
поправила

2022-01-05 10:38 UTC, Elizaveta-1207 commented on src/components/Counter/Counter.jsx
> +      )}
поправила

2022-01-05 10:41 UTC, Elizaveta-1207 commented on src/components/Ingredient/Ingredient.jsx
> +  }, [constructorBuns, constructorIngredients, buns, _id]);
Не согласна. Добавляется же в итоге две булочки и сумма считается, как за две. Соответственное для человека, который делает заказ в интерфейсе сразу отображается, за что он платит и в каком количестве.

2022-01-05 10:48 UTC, merged